version: "3.9"

services:

  django:
    container_name: btspti-Django
    build: .
    restart: always
    ports:
    - 8008:8000
    volumes:
    - ./:/app
    depends_on:
      - db

  db:
    image: postgres:14.3-alpine3.16
    container_name: btspti-db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=base
      - POSTGRES_USER=magoreal
      - POSTGRES_PASSWORD=ojalaque
    volumes:
      - ./db:/var/lib/postgresql/data
